// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8imWI7Tsdw7aGgnfzMNWihSXF0Ub1ppc',
    appId: '1:402410009513:web:eeb6257a4dc213cef9cab8',
    messagingSenderId: '402410009513',
    projectId: 'gym-rat-v2',
    authDomain: 'gym-rat-v2.firebaseapp.com',
    storageBucket: 'gym-rat-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdw88j2i3olCEzOInYknpa-_9A0YNxVA',
    appId: '1:402410009513:android:66a6556bfdab5834f9cab8',
    messagingSenderId: '402410009513',
    projectId: 'gym-rat-v2',
    storageBucket: 'gym-rat-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUry8d7MplZDN94dEmSCYdTCXoRD53UY',
    appId: '1:402410009513:ios:baa47eaa6295f98df9cab8',
    messagingSenderId: '402410009513',
    projectId: 'gym-rat-v2',
    storageBucket: 'gym-rat-v2.appspot.com',
    iosClientId: '402410009513-6hfe09ephov0tu8oq2jqvvei43pb1euo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymRatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUry8d7MplZDN94dEmSCYdTCXoRD53UY',
    appId: '1:402410009513:ios:baa47eaa6295f98df9cab8',
    messagingSenderId: '402410009513',
    projectId: 'gym-rat-v2',
    storageBucket: 'gym-rat-v2.appspot.com',
    iosClientId: '402410009513-6hfe09ephov0tu8oq2jqvvei43pb1euo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymRatV2',
  );
}
